### ISSUE TITLE
"Contents" sidebar starts overlapping content at 1,280 pixels wide

### ISSUE THREAD

**Issue by jkachmar** [commercialhaskell/stackage-server#278]
Originally from commercialhaskell/stackage#4911 (cc @tfausak)
> I hope this is the right place to open this issue! Please let me know if it isn't and I'll move it where it belongs.
> 
> I recently noticed that the Haddock output on Stackage looks different. In general I like it, but I've noticed a problem at a certain break point. The "Contents" sidebar starts overlapping the content when the viewport is 1,280 pixels wide (or wider). Here's an example from [Scotty's documentation](https://www.stackage.org/haddock/nightly-2019-10-13/scotty-0.11.5/Web-Scotty.html):
> 
> ![Screen Shot 2019-10-13 at 20 09 59](https://user-images.githubusercontent.com/408753/66724572-722f8c80-edf5-11e9-88fb-5f76bcaad55b.png)
> 
> At 1,279 (and narrower) pixels wide, the "Contents" sidebar goes to the right and nudges content out of the way. Here's another example from Scotty's documentation:
> 
> ![Screen Shot 2019-10-13 at 20 11 05](https://user-images.githubusercontent.com/408753/66724582-98552c80-edf5-11e9-83ee-aa38ff337a10.png)
> 
> I don't have a suggestion for a solution here, but I do feel that all content should be visible at all breakpoints. Thanks!

**Comment by snoyberg** [comment]
If we append `?style=plain` to the URL, this problem seems to disappear. Can you confirm? If so, it looks like a mismatch between the Stackage custom CSS and the new Haddocks. Options I see are:

1. Turn the custom styling off by default
2. Fix the CSS for the new CSS style
3. Try to do something conditional based on the Haddock version (harder)

I lean towards (1), with (2) open to anybody interested in taking a stab at it. I'll push a commit to do so. In the meanwhile, pinging @chrisdone as well.

**Comment by tfausak** [comment]
Yup, adding `?style=plain` fixes it.

**Comment by snoyberg** [comment]
The commit above deployed to production, so in theory that query string is no longer necessary.
