### ISSUE TITLE
Hoogle Search Fails

### ISSUE THREAD

**Issue by JavariaGhafoor** [commercialhaskell/stackage-server#323]
For whatever I search, I get this error:

<img width="549" alt="Screenshot 2023-12-29 at 5 48 20 PM" src="https://github.com/fpco/stackage-server/assets/92731587/74dda81b-9dd0-4aad-8aaf-98d4d4a09292">

**Comment by chreekat** [comment]
@JavariaGhafoor this is fixed now - sorry for the wait!

See https://github.com/commercialhaskell/stackage/issues/7258.

**Comment by chreekat** [comment]
Arg. I will investigate.

**Comment by tomjaguarpaw** [comment]
Because this has become a recurring complaint maybe an automated check would be worthwhile?

**Comment by chreekat** [comment]
I think one lesson learned is that I should have put that stuff in *first*. As it is, it's high on the list of my "important + urgent" followup tasks for the handover.

**Comment by chreekat** [comment]
@tomjaguarpaw I've discovered how to manually repair a missing hoogle database by throwing files around on the server. Search should be working again. Unfortunately there is an underlying problem that will need to be fixed before the next LTS is released, or it will happen again.

**Comment by chreekat** [comment]
There are three underlying problems that conspired to create this outage.

1. R2 is performing badly for PutObject and ListObjects commands. 
2. I had misconfigured the cache in front of the bucket such that it was caching 404's.
3. Stackage decides a new snapshot is "ready" before the Hoogle database has finished being prepared.

I believe what happened is that Stackage decided lts-22.14 was available (3) before the database finished getting uploaded (1), leading to a window of time where Hoogle searches would come up empty. This time window was long enough that someone (or some thing) did, in fact, perform a Hoogle search. Stackage hit a 404 looking for the database, and it was dutifully cached by Cloudflare (2). Thus, even after the PutObject finished, Stackage kept getting a 404 for the database.

I have fixed (2). I was already working with Cloudflare staff to resolve (1). I'm still digging into (3), because it's honestly a problem even on its own. I would like to ensure that a snapshot doesn't "go live" on Stackage until the Hoogle database is already in place.

**Comment by chreekat** [comment]
I also discovered a mystery: Stackage wasn't getting a 404 for the database, but it wasn't finding it, either. The logs said nothing. But *every* non-200 status code had logging associated with it! Where was the trail of execution going? Was some exception happening before the log lines could fire?

But I think I figured it out. 

```haskell
case responseStatus res of
    status
        | status == status200 -> do
            createDirectoryIfMissing True $ takeDirectory fp
            withBinaryFileDurableAtomic fp WriteMode $ \h ->
                runConduitRes $
                bodyReaderSource (responseBody res) .| ungzip .|
                sinkHandle h
            return $ Just fp
        | status == status404 -> do
            logWarn $ "NotFound: " <> display (hoogleUrl name bucketUrl)
            return Nothing
        | otherwise -> do
            body <- liftIO $ brConsume $ responseBody res
            mapM_ (logWarn . displayBytesUtf8) body
-- here     ^^^^^^
            return Nothing
```

If the response body is empty, the `mapM_` results in no messages sent! :D
